name: VasiarInventario

main: Creadores\Vasiar\Main

version: 1.0.0

api: 2.0.0

load: POSTWORLD

author: Creadores

description: Vacía tu inventario!

website: https://github.com/Trollhunters501

commands: 
 vi:
  description: "Vacía tu inventario!"
  usage: "/vi" 
  permission: true
